version: '3'

services:
  app:
    container_name: task-scheduler
    image: felipeagger/task-scheduler-huey:latest
    #build: '.'
    environment:
      REDIS_HOST: redis
      PORT: 8088
    depends_on:
      - redis
    ports:
      - '8088:8088'
    restart: always

  redis:
    container_name: redis
    image: redis:latest    
    ports:
      - '6379:6379'
    restart: always